auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
#exclude: [shower,themes]

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: John Sun
    # url:  http://example.com/
    company:
        name: .
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
